# building pipelines
name: Nasa Project CLI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    env:
      CI: true  # the Create React app test script will know that we're running any continuous integration environment and will disable watch mode.This is a built in feature of the Create React app test script, the one that we use to test our clients project, but we could put any different kind of variable here.
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js version 16
        uses: actions/setup-node@v1
        with:
          node-version: "16"
      - run: npm install
      - run: npm run build --prefix client
